-- 028_go_rewrite.sql — retired; it creates nothing (idempotent).
--
-- This migration once filled two gaps for an integration that fetched files
-- from outside the catalog: a job table of its own and a unique index on the
-- read model of its job events. The core no longer carries that integration
-- (files enter the catalog through the scanner and POST /api/ingest only), so a
-- new catalog does not get either object.
--
-- A catalog that applied this file keeps com_nalet_katalog_trailerjobs and the
-- index idx_downloadjobs_client; nothing reads or writes them any more.
-- Dropping them is a decision of its own, not one a migration makes in passing.
SELECT 1;
