CREATE UNIQUE INDEX com_nalet_katalog_downloadjobs_pkey ON public.com_nalet_katalog_downloadjobs USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_enrichmentjobs_pkey ON public.com_nalet_katalog_enrichmentjobs USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_enrichmentstatuscodes_pkey ON public.com_nalet_katalog_enrichmentstatuscodes USING btree (code)
CREATE UNIQUE INDEX com_nalet_katalog_genres_pkey ON public.com_nalet_katalog_genres USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_itemartwork_pkey ON public.com_nalet_katalog_itemartwork USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_itemartworkdata_pkey ON public.com_nalet_katalog_itemartworkdata USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_itemchapters_pkey ON public.com_nalet_katalog_itemchapters USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_itemdiagnostics_pkey ON public.com_nalet_katalog_itemdiagnostics USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_itemexternalids_pkey ON public.com_nalet_katalog_itemexternalids USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_itemgenres_pkey ON public.com_nalet_katalog_itemgenres USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_itempeople_pkey ON public.com_nalet_katalog_itempeople USING btree (id)
CREATE INDEX idx_processingsteps_inflight ON public.com_nalet_katalog_itemprocessingsteps USING btree (startedat) WHERE ((status)::text = 'in_progress'::text)
CREATE UNIQUE INDEX com_nalet_katalog_itemprocessingsteps_pkey ON public.com_nalet_katalog_itemprocessingsteps USING btree (id)
CREATE UNIQUE INDEX idx_processingsteps_item_step ON public.com_nalet_katalog_itemprocessingsteps USING btree (item_id, step)
CREATE INDEX idx_processingsteps_pending ON public.com_nalet_katalog_itemprocessingsteps USING btree (step) WHERE ((status)::text = 'pending'::text)
CREATE UNIQUE INDEX com_nalet_katalog_items_pkey ON public.com_nalet_katalog_items USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_itemtags_pkey ON public.com_nalet_katalog_itemtags USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_itemtrailerlinks_pkey ON public.com_nalet_katalog_itemtrailerlinks USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_mediasegments_pkey ON public.com_nalet_katalog_mediasegments USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_people_pkey ON public.com_nalet_katalog_people USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_playbackassets_pkey ON public.com_nalet_katalog_playbackassets USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_scanjobs_pkey ON public.com_nalet_katalog_scanjobs USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_settings_pkey ON public.com_nalet_katalog_settings USING btree (id)
CREATE UNIQUE INDEX com_nalet_katalog_subtitleassets_pkey ON public.com_nalet_katalog_subtitleassets USING btree (id)
